### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by Obitech96** [venosyd/flutter_web_app#1]
Hi 
I tried to change the website address but without any results...
You can explain me how I must change the program for using your program? 
I am trying from 2 days with any success...
Thank you so much
Marco

**Comment by sergioelisan** [comment]
I updated the README file in the project home. It was my mistake forgetting basic instructions like adding the lib to the project pubspec.yaml.

**Comment by sergioelisan** [comment]
There is a catch!!

Sometimes a website, on Android or iOS, can't be loaded on a app webview! It's something like "CLEAR_TEXT" restrictions, a security issue. The page can be blank when it occurs.

So, test if the site is enabled to the app is mandatory before release the app

**Comment by Obitech96** [comment]
> There is a catch!!
> 
> 
> 
> Sometimes a website, on Android or iOS, can't be loaded on a app webview! It's something like "CLEAR_TEXT" restrictions, a security issue. The page can be blank when it occurs.
> 
> 
> 
> So, test if the site is enabled to the app is mandatory before release the app

Perfect tank you so much!
Leave me 1 or 2 our, when I will arrive at home I will try

**Comment by Obitech96** [comment]
So i must paste this part: 


```library myweb.app;

import 'package:flutter/material.dart';
import 'package:flutter_web_app/flutter_web_app.dart';

void main() => runApp(
    WebApp(
        url: 'https://<your-website-url>', 
        statusBarColor: <your-preferred-color>
        )
    );


```

in your flutter_webb_app.dart ?
In which part?

**Comment by Obitech96** [comment]
I created a file call "main.dart" in lib where I putted the code with link and status bar color than I putted in pubspect.yaml
"flutter_web_app:
git: git@....."

But I can't run the program in the virtual device... I don't know why...
He show me in the upper part get/pub upgrade but every time if I click on one of those I say me "exit code 0"
I tried with flutter doctor and everything it's ok
You can help me? I have no idea what is wrong... if you think is better share my code changed, no problem I will do it immediately 
Thanks a lot
Marco

ps. it show me this error:
`AndroidManifest.xml could not be found.
Please check C:\Users\Riccardo\Downloads\flutter_web_app-master 16\flutter_web_app-master\android\AndroidManifest.xml for errors.
No application found for TargetPlatform.android_x86.
Is your project missing an android\AndroidManifest.xml?
Consider running "flutter create ." to create one.
`

**Comment by sergioelisan** [comment]
Create a fresh project with "flutter create" as described in the README.md
You don't need to clone this repository, the line in the pubspec.yaml will pull it.

1. Create the app using flutter create
2. Edit the pubspec.yaml as described
3. In the lib/main.dart (generated by the flutter create command), delete everything and put the code demonstrated in the README
4. flutter run

**Comment by sergioelisan** [comment]
> I created a file call "main.dart" in lib where I putted the code with link and status bar color than I putted in pubspect.yaml
> "flutter_web_app:
> git: git@....."
> 
> But I can't run the program in the virtual device... I don't know why...
> He show me in the upper part get/pub upgrade but every time if I click on one of those I say me "exit code 0"
> I tried with flutter doctor and everything it's ok
> You can help me? I have no idea what is wrong... if you think is better share my code changed, no problem I will do it immediately
> Thanks a lot
> Marco
> 
> ps. it show me this error:
> `AndroidManifest.xml could not be found. Please check C:\Users\Riccardo\Downloads\flutter_web_app-master 16\flutter_web_app-master\android\AndroidManifest.xml for errors. No application found for TargetPlatform.android_x86. Is your project missing an android\AndroidManifest.xml? Consider running "flutter create ." to create one. `

This error is happening because your are downloading this repo and editing the lib/main file. This repository is a lib you can integrate in your project ;)
