### ISSUE TITLE
You might want to change package dependency to a url

### ISSUE THREAD

**Issue by mowolf** [venosyd/flutter_web_app#2]
You might want to change

`    git: git@github.com:venosyd/flutter_web_app.git
`

to 

`    git: https://github.com/venosyd/flutter_web_app.git
`

Else pub tries to get the repo via ssh, and on my part failed (even though the repo is public, it complained that I don't have the right to read).

**Comment by sergioelisan** [comment]
Thank u!

I didn`t have notice that, so I updated this and the others repositories with the same change!
