### ISSUE TITLE
unsound null safety

### ISSUE THREAD

**Issue by coachlogicdev** [venosyd/flutter_web_app#3]
I am getting the unsound null safety error resulting in failed compile.  I tried running as follows: 
 flutter run --no-sound-null-safety but this does not work.   Using flutter 2.2.3.

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:                                              
                                                                        
 - package:flutter_web_app   
Unhandled exception:                                                    
Bad state: Unsupported Null Safety mode                                 
NonNullableByDefaultCompiledMode.Invalid, in null.

**Comment by sergioelisan** [comment]
I will update this package to support null safety tonight.

**Comment by coachlogicdev** [comment]
Any update on this change?  Thanks Sergio

**Comment by sergioelisan** [comment]
Updated!
