### ISSUE TITLE
Build issue : package visibility

### ISSUE THREAD

**Issue by coachlogicdev** [venosyd/flutter_web_app#4]
running into issues building with the latest.  

Xcode's output:
↳
    Error: Couldn't resolve the package 'flutter_web_app' in 'package:flutter_web_app/flutter_web_app.dart'.
    lib/main.dart:4:8: Error: Not found: 'package:flutter_web_app/flutter_web_app.dart'
    import 'package:flutter_web_app/flutter_web_app.dart';
           ^
    lib/main.dart:15:15: Error: Method not found: 'WebApp'.
            home: WebApp(
                  ^^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_web_app%2Fflutter_web_app.dart; message=StandardFileSystem only supports file:* and data:*
    URIs)
    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:36:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:599:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:738:21)
    <asynchronous suspension>

**Comment by sergioelisan** [comment]
Run "flutter clean" inside your flutter project, enter the ios/ directory and run "pod install". After this commands, return to the project root and "flutter run". This may be a clashing plugin dynlib causing problems. I will verify in my installation here. Try to run the example inside the flutter_web_app/ project too.

**Comment by coachlogicdev** [comment]
A podfile is not being created in the iOS directory when I run flutter create --org performalyze coachlogic

I copied one from example and ran flutter run at the project level and got:

sh-3.2$ flutter run
Running "flutter pub get" in coachlogic...                         685ms
Launching lib/main.dart on Chrome in debug mode...
Error: Couldn't resolve the package 'flutter_web_app' in 'package:flutter_web_app/flutter_web_app.dart'.
lib/main.dart:4:8: Error: Not found: 'package:flutter_web_app/flutter_web_app.dart'
import 'package:flutter_web_app/flutter_web_app.dart';                  
       ^                                                                
lib/main.dart:15:15: Error: Method not found: 'WebApp'.                 
        home: WebApp(                                                   
              ^^^^^^                                                    
Unhandled exception:                                                    
NoSuchMethodError: The getter 'path' was called on null.                
Receiver: null                                                          
Tried calling: path                                                     
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)    
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:162:65)

**Comment by sergioelisan** [comment]
flutter_web_app is a package, you can use inside your app. the example/ project folder is an app using the flutter_web_app/ package. you can't run the package outside an application, that's the problem you described.

**Comment by coachlogicdev** [comment]
I am not sure of the project and folder structure required to give visibility to the package flutter_web_app   I 

1.  Created the project using : flutter create --org performalyze coachlogic.   This creates a folder "coachlogic" at the same directory level as flutter_web_app folder.

2.  cd coachlogic\lib.  modify main.dart to match directions.
3. cd ..
4. flutter run

5.   This is where the coachlogic app is not able to resolve flutter_web _app

Questions:
1.   I tried copying flutter_web_app folder and adding to the coachlogic folder.   flutter run ailed with same error.
2. I tried copying coachlogic into flutter_web_app folder.  flutter run failed with same error
3. I am new to flutter and do not know how the app looks for paths.   Is there a something similar to a Java CLASSPATH to tell it to look for flutter_web_app\flutter_web_app.dart ?
4.

**Comment by sergioelisan** [comment]
You created your project correctly, but the library import is wrong. Inside your project's folder, in the **pubspec.yaml** file, add the line:

```
dependencies:
  flutter:
    sdk: flutter
  ...
  flutter_web_app:
     git: https://github.com/venosyd/flutter_web_app.git
  ...
```

You don´t have to download this folder, or clone this project (only if you want to extend, modify...).  Just add the lines above in the pubspec.yaml and you can use the lib.

**Comment by coachlogicdev** [comment]
Thanks that worked, however, it still looks like flutter is not finding everything:

sh-3.2$ flutter clean
Cleaning Xcode workspace...                                      2,992ms
Deleting build...                                                    2ms
Deleting .dart_tool...                                               0ms
Deleting .packages...                                                0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
sh-3.2$ flutter run
Running "flutter pub get" in coachlogic...                       1,991ms
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             19.6s
This app is linked to the debug service: ws://127.0.0.1:61172/DZSqi9X1tP8=/ws
Debug service listening on ws://127.0.0.1:61172/DZSqi9X1tP8=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
Error: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
    at Object.throw_ [as throw] (http://localhost:61145/dart_sdk.js:5041:11)
    at MethodChannel._invokeMethod (http://localhost:61145/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:61145/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:61145/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:61145/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:61145/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:61145/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:61145/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:61145/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:61145/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:61145/dart_sdk.js:37532:13)
    at http://localhost:61145/dart_sdk.js:33303:9
Error: MissingPluginException(No implementation found for method launch on channel flutter_webview_plugin)

**Comment by sergioelisan** [comment]
This plugin is for mobile (Android, iOS), i believe even the desktop will not work.

**Comment by coachlogicdev** [comment]
Working great.   If you want to mix pure Flutter app with flutter_web_app, would you use this approach ?

https://flutter.dev/docs/development/add-to-app/multiple-flutters

**Comment by sergioelisan** [comment]
Wow. Flutter continues to surprises me! I will study this new functionality and improve this library! Thank you
